# -*- coding: utf-8 -*-
"""NugasUasPCD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eU7sEJcAiCAtUm9CsaUHb0wU6b3UZ7t4
"""

import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
file = files.upload()

pip install opencv-contrib-python

cv2.face.LBPHFaceRecognizer_create()

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

img = cv2.imread('/content/drive/MyDrive/Folder saya/foto3.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray, 1.25, 6)

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

imgplot = plt.imshow(img)

from google.colab.patches import cv2_imshow
cv2_imshow(img)